name: seegle
description: "Seegle is a dynamic and engaging platform designed to bring people together through shared interests and meaningful discussions. Whether you're passionate about gaming, fitness, coding, or any other hobby, Seegle allows you to create and join Flocks—communities where like-minded individuals connect, collaborate, and share insights. With real-time discussions, customizable privacy settings, and a user-friendly experience, Seegle ensures that every conversation feels personal and relevant. Public Flocks encourage open interaction, while private Flocks offer a more exclusive space for deeper engagement. Seegle also integrates push notifications, ensuring you never miss an important update, and features moderation tools to keep your community safe and engaging. Whether you're looking to share knowledge, organize events, or simply chat with people who share your interests, Seegle is the perfect place to build and grow your digital community."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  flutter_signin_button: ^2.0.0
  crypto: ^3.0.3
  cloud_firestore: ^5.6.5
  permission_handler: ^12.0.0+1
  flutter_native_splash: ^2.4.0
  firebase_analytics: ^11.4.4
  get: ^4.6.6
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  url_launcher: ^6.2.11
  firebase_messaging: ^15.2.4
  slide_to_confirm: ^1.1.0
  getwidget: ^6.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_linkify: ^6.0.0
  provider: ^6.0.2
  inner_shadow_widget: ^0.0.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  camera: ^0.11.0
  path_provider: ^2.0.11
  video_player: ^2.2.11
  firebase_storage: ^12.4.4
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.17
  metadata_fetch: ^0.4.2
  giphy_get:
    path: giphy_get
  flutter_neumorphic_plus: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter_native_splash:
  color: "#b2b2b2"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file.
  image: assets/icons/icon.png

  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#333333"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/sign_in/
    - assets/icons/globe_gull.svg
    - assets/icons/shield_gull.svg
    - assets/fonts/testfile.txt

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/NexaBold.otf
        - asset: assets/fonts/NexaLight.otf
    - family: Seegle
      fonts:
        - asset: assets/fonts/Seegle.ttf
    - family: Cormorant
      fonts:
        - asset: assets/fonts/Cormorant-Regular.ttf
        - asset: assets/fonts/Cormorant-Bold.ttf
        - asset: assets/fonts/Cormorant-Italic.ttf
        - asset: assets/fonts/Cormorant-BoldItalic.ttf
