// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3NpGiwFXVclkIO0gfvFVgnkxptq6jhw',
    appId: '1:570472137763:web:0edf5adbe3e10fa2b89d96',
    messagingSenderId: '570472137763',
    projectId: 'seegle-e1eb3',
    authDomain: 'seegle-e1eb3.firebaseapp.com',
    storageBucket: 'seegle-e1eb3.appspot.com',
    measurementId: 'G-D70CN5W0YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OtJs2IMAD0xcuweY22ErM7_2_JqXjTE',
    appId: '1:570472137763:android:aceed3024c4a94feb89d96',
    messagingSenderId: '570472137763',
    projectId: 'seegle-e1eb3',
    storageBucket: 'seegle-e1eb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtyveQV5seE1kTEv8Xg_ujwcvsm8qtrrc',
    appId: '1:570472137763:ios:f27e274634d7d23fb89d96',
    messagingSenderId: '570472137763',
    projectId: 'seegle-e1eb3',
    storageBucket: 'seegle-e1eb3.appspot.com',
    iosBundleId: 'com.sdotlabs.seegle',
  );
}
